default:
  image: node:24-slim
  before_script:
    - corepack enable
    - pnpm i

build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH
  image: node:24-slim
  script:
    - corepack enable
    - pnpm i
    - pnpm pack

publish:
  stage: deploy
  script:
    - echo "@inp-net:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - pnpm publish