build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG !~ /^v\d+\.\d+\.\d+.*$/
  image: node:24-slim
  script:
    - corepack enable
    - pnpm i
    - pnpm pack

publish:
  stage: publish
  script:
    - echo "@inp-net:registry=https://git.inpt.fr/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//git.inpt.fr/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - pnpm publish --no-git-checks
  rules:
    - if: $CI_COMMIT_TAG